---

version: 2
updates:

  # Maintain dependecies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependecies for bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
