---

# Build-Deploy Jekyll site to gh-pages branch
name: build-deploy.
on:
  push:
    branches:
      - main

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby and Build site.
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Build _site with Jekyll.
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages.
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: _site
