---
#Auto approves and automerges pull requests on GitHub Actions made by dependabot on Ruby Gems. Assigns me the issue if it has < 90% compatibility score.

name: AutoApprove && Automerge Dependabot Bundler Dependencies

on:
  pull_request:
    branches:
      - main
    types: [opened]
permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      PR_URL: ${{github.event.pull_request.html_url}}

    steps:
      - name: Fetch Dependabot PRs metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.2
        with:
          compat-lookup: true
          github-token: "${{ secrets.PAT_DEPENDABOT }}"

      - name: Get PR details
        run: |
          gh pr view --json "$PR_URL" && gh pr view --comments "$PR_URL"

      - name: Add a label that notes the PR updates Ruby Gems
        run: gh pr edit "$PR_URL" --add-label "ruby_gem_updates"

      - name: Approve Dependabot PRs
        run: gh pr review --approve "$PR_URL"

      - name: Merge dependency if compatibility is >=90%
        if: ${{ steps.dependabot-metadata.outputs.compatibility-score >= 90}}
        run: gh pr merge --auto --merge "$PR_URL"

      - name: If compatibility score wasn't present or score is <90% assign and notify.
        if: ${{ failure() }} # Runs only if previous step failed or has been cancelled.
        run: gh pr edit "$PR_URL" --assignee "@me"

